### PR TITLE
Handle disconnect with non connected client. Refers to https://github…

### PR DESCRIPTION
**Pull request by radekg**
….com/erlio/vmq_commons/issues/14.

### CODE REVIEW

**Comment by radekg** [comment]
As documented on #14, calling `disconnect` on not connected client should stop the FSM instead of ignoring the `disconnect` request.

**Comment by ioolkos** [comment]
Hi @radekg 
thank you very much for your PR! :)
I think what you propose makes perfect sense. Although it will probably lead to some general decision we'll have to make on the Client Lib state machine:

Client App -> Client Lib -> MQTT Broker

For example, what if you issue messages from the Client App to the Client Lib FSM that is not yet ready? Should we buffer them? Currently we ignore them, just like the disconnect.

**Comment by radekg** [comment]
Hey @ioolkos, sounds like another PR ;) I can help with this (and things like hard coded reconnect timeout. Would you like to see these decisions made before this PR is merged or can we possibly focus on that afterwards, one by one?

**Comment by ioolkos** [comment]
I think it would make sense to make gen_mqtt into a more general client lib. (it already is very flexible, not trying to optimise for performance for example).

I'd would like any change to be safe regarding the following:
- not break the VerneMQ bridge plugin
- not break the mqtt_worker in vmq_mzbench
- be nice to projects like GenMQTT (@gausby) that use vmq_commons

@dergraf @larshesel fine with merging this? (and my remarks above?)

**Comment by dergraf** [comment]
I am on the same page here. It would be great to have a generalized MQTT client lib in Erlang. For the moment I'd say if @radekg PR isn't breaking any of the mentioned projects it is good to merge.

**Pull request merged**
